### PR TITLE
fix: avatars

### LINKED ISSUE #218: Pictique demonstrates wrong avatars in some cases
# Description

Pictique demonstrates wrong avatars in some cases
# Steps to reproduce

1. Open Pictique
2. Click Search and find Alex 3 (no any avatar shown)
3. Click on Alex 3 and open his profile
4. You see lion image instead of Alex face (which he installed for his profile in Blabsy and which is visible there)

Image

# Expected behavior

All avatars should be the same and correct

# Supporting Media

# Desktop:

(please complete the following information)

-   Device: [eg. Mobile/PC]
-   OS: [e.g. iOS/Windows]
-   Browser: [e.g. chrome, safari]
-   Version: [e.g. 22]

# Additional Context

### PR DESCRIPTION
**Pull request by ghost**
# Description of change
- fixed create post modal buttons
- avatar fixed when clicked from searched user

## Issue Number
closes #218 

## Type of change
- Update (a change which updates existing functionality)
- Fix (a change which fixes an issue)

## How the change has been tested
CI and Manual

## Change checklist
- [x] I have ensured that the CI Checks pass locally
- [x] I have removed any unnecessary logic
- [x] My code is well documented
- [x] I have signed my commits
- [x] My code follows the pattern of the application
- [x] I have self reviewed my code

## Summary by CodeRabbit

- **Chores**
	- Updated environment URLs for the Blabsy platform to use a secure external address.

- **Style**
	- Improved spacing and button styling in the post creation modal for Pictique.
	- Reordered CSS class sequences in various components for consistency.
	- Added size attributes to buttons for uniform appearance.

- **Refactor**
	- Adjusted event binding syntax and added accessibility directive comments in the post creation modal for better compatibility and linting compliance.
	- Simplified property handling and typing in post and profile components.
	- Enhanced prop declarations and renamed properties for clarity.
	- Removed unused imports and improved safe data access in profile messaging.
	- Reformatted code indentation and string delimiters across multiple modules for consistency.

### CODE REVIEW

File: platforms/pictique/src/routes/(protected)/discover/+page.svelte [hunk 1]
```diff
@@ -39,6 +39,10 @@
 			clearTimeout(debounceTimer);
 		};
 	});
+
+	$effect(() => {
+		console.log($searchResults);
+	})
 </script>
```
Comment (sosweetham) [inline platforms/pictique/src/routes/(protected)/discover/+page.svelte:46]: remove

**Review by sosweetham — APPROVED** [review]
